#ifndef CYGONCE_PKGCONF_HAL_ARM_H
#define CYGONCE_PKGCONF_HAL_ARM_H
/*
 * File <pkgconf/hal_arm.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGINT_HAL_ARM_THUMB_ARCH 1
#define CYGINT_HAL_ARM_THUMB_ARCH_1
#define CYGBLD_ARM_ENABLE_THUMB_INTERWORK 1
#define CYGINT_HAL_ARM_BIGENDIAN 0
#define CYGINT_HAL_ARM_BIGENDIAN_0
#define CYGINT_HAL_ARM_ARCH_ARM7 1
#define CYGINT_HAL_ARM_ARCH_ARM7_1
#define CYGINT_HAL_ARM_ARCH_ARM9 0
#define CYGINT_HAL_ARM_ARCH_ARM9_0
#define CYGINT_HAL_ARM_ARCH_STRONGARM 0
#define CYGINT_HAL_ARM_ARCH_STRONGARM_0
#define CYGINT_HAL_ARM_ARCH_XSCALE 0
#define CYGINT_HAL_ARM_ARCH_XSCALE_0
#define CYGBLD_HAL_ARM_EABI 1
#define CYGPKG_REDBOOT_ARM_LINUX_EXEC 1
#define CYGHWR_REDBOOT_ARM_LINUX_EXEC_ADDRESS 0x00008000
#define CYGHWR_REDBOOT_ARM_LINUX_EXEC_ADDRESS_0x00008000
#define CYGHWR_REDBOOT_ARM_LINUX_TAGS_ADDRESS 0x00000100
#define CYGHWR_REDBOOT_ARM_LINUX_TAGS_ADDRESS_0x00000100
#define CYGINT_HAL_ARM_MEM_REAL_REGION_TOP 0
#define CYGINT_HAL_ARM_MEM_REAL_REGION_TOP_0

#endif
