#ifndef CYGONCE_PKGCONF_SYSTEM_H
#define CYGONCE_PKGCONF_SYSTEM_H
/*
 * File <pkgconf/system.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_VERSION_CURRENT 0x7fffff00
#define CYGPKG_HAL_ARM v3_0
#define CYGPKG_HAL_ARM_v3_0
#define CYGNUM_HAL_ARM_VERSION_MAJOR 3
#define CYGNUM_HAL_ARM_VERSION_MINOR 0
#define CYGNUM_HAL_ARM_VERSION_RELEASE -1
#define CYGPKG_HAL_ARM_AT91 v3_0
#define CYGPKG_HAL_ARM_AT91_v3_0
#define CYGNUM_HAL_ARM_AT91_VERSION_MAJOR 3
#define CYGNUM_HAL_ARM_AT91_VERSION_MINOR 0
#define CYGNUM_HAL_ARM_AT91_VERSION_RELEASE -1
#define CYGBLD_HAL_ARM_VAR_IO_H
#define CYGBLD_HAL_ARM_VAR_ARCH_H
#define CYGPKG_HAL_ARM_AT91SAM7 v3_0
#define CYGPKG_HAL_ARM_AT91SAM7_v3_0
#define CYGNUM_HAL_ARM_AT91SAM7_VERSION_MAJOR 3
#define CYGNUM_HAL_ARM_AT91SAM7_VERSION_MINOR 0
#define CYGNUM_HAL_ARM_AT91SAM7_VERSION_RELEASE -1
#define CYGBLD_HAL_TARGET_H   <pkgconf/hal_arm.h>
#define CYGBLD_HAL_VARIANT_H  <pkgconf/hal_arm_at91.h>
#define CYGBLD_HAL_ARM_VAR_IO_H
#define CYG_HAL_STARTUP ROM
#define CYG_HAL_STARTUP_ROM
#define CYGHWR_MEMORY_LAYOUT_LDI <pkgconf/mlt_arm_at91sam7s256_rom.ldi>
#define CYGHWR_MEMORY_LAYOUT_H <pkgconf/mlt_arm_at91sam7s256_rom.h>
#define CYGPKG_HAL_ARM_AT91SAM7SEK v3_0
#define CYGPKG_HAL_ARM_AT91SAM7SEK_v3_0
#define CYGNUM_HAL_ARM_AT91SAM7SEK_VERSION_MAJOR 3
#define CYGNUM_HAL_ARM_AT91SAM7SEK_VERSION_MINOR 0
#define CYGNUM_HAL_ARM_AT91SAM7SEK_VERSION_RELEASE -1
#define CYGBLD_HAL_PLATFORM_H <pkgconf/hal_arm_at91sam7sek.h>
#define CYGPKG_IO_SPI v3_0
#define CYGPKG_IO_SPI_v3_0
#define CYGNUM_IO_SPI_VERSION_MAJOR 3
#define CYGNUM_IO_SPI_VERSION_MINOR 0
#define CYGNUM_IO_SPI_VERSION_RELEASE -1
#define CYGPKG_DEVS_SPI_ARM_AT91 v3_0
#define CYGPKG_DEVS_SPI_ARM_AT91_v3_0
#define CYGNUM_DEVS_SPI_ARM_AT91_VERSION_MAJOR 3
#define CYGNUM_DEVS_SPI_ARM_AT91_VERSION_MINOR 0
#define CYGNUM_DEVS_SPI_ARM_AT91_VERSION_RELEASE -1
#define CYGPKG_DEVS_USB_AT91 v3_0
#define CYGPKG_DEVS_USB_AT91_v3_0
#define CYGNUM_DEVS_USB_AT91_VERSION_MAJOR 3
#define CYGNUM_DEVS_USB_AT91_VERSION_MINOR 0
#define CYGNUM_DEVS_USB_AT91_VERSION_RELEASE -1
#define CYGPKG_HAL v3_0
#define CYGPKG_HAL_v3_0
#define CYGNUM_HAL_VERSION_MAJOR 3
#define CYGNUM_HAL_VERSION_MINOR 0
#define CYGNUM_HAL_VERSION_RELEASE -1
#define CYGPKG_INFRA v3_0
#define CYGPKG_INFRA_v3_0
#define CYGNUM_INFRA_VERSION_MAJOR 3
#define CYGNUM_INFRA_VERSION_MINOR 0
#define CYGNUM_INFRA_VERSION_RELEASE -1
#define CYGPKG_REDBOOT v3_0
#define CYGPKG_REDBOOT_v3_0
#define CYGNUM_REDBOOT_VERSION_MAJOR 3
#define CYGNUM_REDBOOT_VERSION_MINOR 0
#define CYGNUM_REDBOOT_VERSION_RELEASE -1
#define CYGPKG_ISOINFRA v3_0
#define CYGPKG_ISOINFRA_v3_0
#define CYGNUM_ISOINFRA_VERSION_MAJOR 3
#define CYGNUM_ISOINFRA_VERSION_MINOR 0
#define CYGNUM_ISOINFRA_VERSION_RELEASE -1
#define CYGPKG_LIBC_STRING v3_0
#define CYGPKG_LIBC_STRING_v3_0
#define CYGNUM_LIBC_STRING_VERSION_MAJOR 3
#define CYGNUM_LIBC_STRING_VERSION_MINOR 0
#define CYGNUM_LIBC_STRING_VERSION_RELEASE -1
#define CYGPKG_CRC v3_0
#define CYGPKG_CRC_v3_0
#define CYGNUM_CRC_VERSION_MAJOR 3
#define CYGNUM_CRC_VERSION_MINOR 0
#define CYGNUM_CRC_VERSION_RELEASE -1

#endif
